[Eth]
NetworkId = 56
SyncMode = "full"
DisablePeerTxBroadcast = false
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
TrustDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
EnableTrustProtocol = false
PipeCommit = false
RangeLimit = false
TxLookupLimit = 2350000
TransactionHistory = 2350000
StateHistory = 90000
StateScheme = "hash"
LightPeers = 100
DatabaseCache = 512
DatabaseFreezer = ""
DatabaseDiff = ""
PersistDiff = false
DiffBlock = 86400
PruneAncientData = false
TrieCleanCache = 154
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 102
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
DelayLeftOver = 50000000
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 3000000000
VoteEnable = false
NewPayloadTimeout = 2000000000
DisableVoteAttestation = false

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000
ReannounceTime = 315360000000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 10737418240
PriceBump = 100

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 0
MaxBlockHistory = 0
MaxPrice = 100000000000
IgnorePrice = 4
OracleThreshold = 1000

[Node]
DataDir = "/home/mev-soviet/.ethereum"
IPCPath = "geth.ipc"
HTTPHost = ""
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]
BLSWalletDir = "/home/mev-soviet/.ethereum/bls/wallet"
VoteJournalDir = "/home/mev-soviet/.ethereum/voteJournal"
BatchRequestLimit = 1000
BatchResponseMaxSize = 25000000

[Node.P2P]
MaxPeers = 50
MaxPeersPerIP = 50
NoDiscovery = false
DiscoveryV4 = true
StaticNodes = []
VerifyNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

[Metrics]
HTTP = "127.0.0.1"
Port = 6060
InfluxDBEndpoint = "http://localhost:8086"
InfluxDBDatabase = "geth"
InfluxDBUsername = "test"
InfluxDBPassword = "test"
InfluxDBTags = "host=localhost"
InfluxDBToken = "test"
InfluxDBBucket = "geth"
InfluxDBOrganization = "geth"

